# Generated by Django 4.2.9 on 2025-05-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_nopeople1_product_nopeople2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nopeople1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='nopeople1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nopeople2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='nopeople2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nopeople3',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='nopeople3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nopeople4',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='nopeople4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nopeople5_6',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='nopeople5_6'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nopeople7_8',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='nopeople7_8'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Price'),
        ),
    ]
