# Generated by Django 4.2.9 on 2025-05-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_nopeople1_alter_product_nopeople2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='food_day',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='food day'),
        ),
    ]
